---
services:
  app: &app
    image: decidim-ocl:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - db-init:/db-init
    depends_on:
      - pg
      - cache
      - mail
      - worker
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - RAILS_DB_HOST=pg
      - RAILS_ENV=production
      - RAILS_MAIL_DELIVERY_CONFIG=address:mail,port:1025
      - RAILS_MEMCACHED_HOST=cache
      - RAILS_SERVE_STATIC_FILES=yes
      - SECRET_KEY_BASE=TEST
      - SENTRY_CURRENT_ENV=production
  pg:
    image: postgres
    environment:
      - POSTGRES_USER=decidim_ocl
      - POSTGRES_PASSWORD=7UhEIvi9wFymva3
      - POSTGRES_DB=decidim_ocl_development
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  cache:
    image: memcached:1.5-alpine
    command: [memcached, -l, '0.0.0.0', -p, '11211']

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    links:
      - pg:db
    depends_on:
      - pg

  mail:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'
  worker:
    <<: *app
    depends_on: []
    ports: []
    entrypoint: []
    command: [rake, 'jobs:work']

volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  db-init: {}
...
