INSERT INTO "decidim_organizations" ("id", "name", "host", "default_locale", "available_locales", "created_at", "updated_at", "description", "logo", "twitter_handler", "favicon", "instagram_handler", "facebook_handler", "youtube_handler", "github_handler", "official_img_footer", "official_url", "reference_prefix", "secondary_hosts", "available_authorizations", "header_snippets", "cta_button_text", "cta_button_path", "enable_omnipresent_banner", "omnipresent_banner_title", "omnipresent_banner_short_description", "omnipresent_banner_url", "highlighted_content_banner_enabled", "highlighted_content_banner_title", "highlighted_content_banner_short_description", "highlighted_content_banner_action_title", "highlighted_content_banner_action_subtitle", "highlighted_content_banner_action_url", "highlighted_content_banner_image", "tos_version", "badges_enabled", "send_welcome_notification", "welcome_notification_subject", "welcome_notification_body", "users_registration_mode", "id_documents_methods", "id_documents_explanation_text", "user_groups_enabled", "smtp_settings", "colors", "force_users_to_authenticate_before_access_organization", "omniauth_settings", "rich_text_editor_in_public_views", "time_zone") VALUES
(1, '{"de": "Decidim Zürich"}'::jsonb,	'localhost',	'de',	'{en,de,fr,it}',	'2020-04-22 08:05:30.883513',	'2020-04-22 08:05:30.929182',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'quwi',	'{}',	'{}',	NULL,	NULL,	NULL,	'0',	NULL,	NULL,	NULL,	'0',	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	'2020-04-22 08:05:30.922317',	'1',	'1',	NULL,	NULL,	0,	'{online}',	'{}',	'1',	'{"from": "decidim@puzzle.ch", "port": 1025, "address": "mail", "user_name": "decidim@puzzle.ch", "encrypted_password": null}',	'{}',	'0',	'{"omniauth_settings_developer_icon": "", "omniauth_settings_developer_enabled": false}',	'0',	'UTC');

INSERT INTO "decidim_content_blocks" ("decidim_organization_id", "manifest_name", "scope_name", "settings", "published_at", "weight", "images", "created_at", "updated_at") VALUES
(1,	'hero',	'homepage',	NULL,	'2020-04-22 08:05:30.989317',	10,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'sub_hero',	'homepage',	NULL,	'2020-04-22 08:05:31.011785',	20,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'highlighted_content_banner',	'homepage',	NULL,	'2020-04-22 08:05:31.020832',	30,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'how_to_participate',	'homepage',	NULL,	'2020-04-22 08:05:31.0311',	40,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'last_activity',	'homepage',	NULL,	'2020-04-22 08:05:31.039948',	50,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'stats',	'homepage',	NULL,	'2020-04-22 08:05:31.047591',	60,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'footer_sub_hero',	'homepage',	NULL,	'2020-04-22 08:05:31.054693',	70,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317'),
(1,	'upcoming_events',	'homepage',	NULL,	'2020-04-22 08:05:31.061716',	80,	'{}', '2020-04-22 08:05:30.989317', '2020-04-22 08:05:30.989317');

INSERT INTO "decidim_contextual_help_sections" ("section_id", "organization_id", "content") VALUES
('participatory_processes',	1,	'{"de": "<p>A <strong>Partizipationsprozess</strong> ist eine Folge von Partizipations Aktivitäten (zB zuerst eine Umfrage ausfüllen, dann Vorschläge machen, so dass sie diskutiert in face-to-face oder virtuellen Sitzungen, und sie schließlich die Priorisierung) mit dem Ziel , die Definition und Treffen eine Entscheidung zu einem bestimmten Thema.</p> <p>Beispiele für partizipatorische Prozesse sind: ein Verfahren zur Wahl von Ausschussmitgliedern (bei dem die Kandidaturen zuerst präsentiert, anschließend debattiert und schließlich eine Kandidatur ausgewählt wird), die Bürgerhaushalte (bei denen Vorschläge gemacht, wirtschaftlich bewertet und mit dem verfügbaren Geld abgestimmt werden). ein strategischer Planungsprozess, die gemeinschaftliche Ausarbeitung einer Vorschrift oder Norm, die Gestaltung eines städtischen Raums oder die Erstellung eines öffentlichen Planes.</p>\n", "en": "<p>A <strong>participatory process</strong> is a sequence of participatory activities (e.g. first filling out a survey, then making proposals, discussing them in face-to-face or virtual meetings, and finally prioritizing them) with the aim of defining and making a decision on a specific topic.</p> <p>Examples of participatory processes are: a process of electing committee members (where candidatures are first presented, then debated and finally a candidacy is chosen), participatory budgets (where proposals are made, valued economically and voted on with the money available), a strategic planning process, the collaborative drafting of a regulation or norm, the design of an urban space or the production of a public policy plan.</p>\n"}'),
('assemblies',	1,	'{"de": "<p>Eine Versammlung ist eine Gruppe von Mitgliedern einer Organisation, die sich regelmäßig treffen, um Entscheidungen über einen bestimmten Bereich oder einen bestimmten Bereich der Organisation zu treffen.</p> <p>Versammlungen halten Meetings ab, einige sind privat und andere sind offen. Wenn sie offen sind, ist es möglich, an ihnen teilzunehmen (z. B. Teilnahme, wenn die Kapazität es erlaubt, Punkte auf die Tagesordnung setzen oder Vorschläge und Entscheidungen dieses Organs kommentieren).</p> <p>Beispiele: Eine Generalversammlung (die einmal im Jahr zusammentritt, um die wichtigsten Aktionslinien der Organisation sowie ihre Exekutivorgane per Abstimmung festzulegen), ein Gleichstellungsbeirat (der alle zwei Monate zusammentritt, um Vorschläge zur Verbesserung der Geschlechterbeziehungen vorzulegen In der Organisation sind eine Evaluierungskommission (die sich jeden Monat zur Überwachung eines Prozesses trifft) oder eine Garantieeinrichtung (die Vorfälle, Missbräuche oder Vorschläge zur Verbesserung der Entscheidungsverfahren sammelt) Beispiele für Versammlungen.</p>\n", "en": "<p>An <strong>assembly</strong> is a group of members of an organization who meet periodically to make decisions about a specific area or scope of the organization.</p> <p>Assemblies hold meetings, some are private and some are open. If they are open, it is possible to participate in them (for example: attending if the capacity allows it, adding points to the agenda, or commenting on the proposals and decisions taken by this organ).</p> <p>Examples: A general assembly (which meets once a year to define the organisation''s main lines of action as well as its executive bodies by vote), an equality advisory council (which meets every two months to make proposals on how to improve gender relations in the organisation), an evaluation commission (which meets every month to monitor a process) or a guarantee body (which collects incidents, abuses or proposals to improve decision-making procedures) are all examples of assemblies.</p>\n"}');

INSERT INTO "decidim_searchable_resources" ("content_a", "content_b", "content_c", "content_d", "locale", "datetime", "decidim_scope_id", "decidim_participatory_space_type", "decidim_participatory_space_id", "decidim_organization_id", "resource_type", "resource_id", "created_at", "updated_at") VALUES
('Puzzle',	'',	'',	'',	'en',	'2020-04-22 08:05:31.243452',	NULL,	NULL,	NULL,	1,	'Decidim::User',	1,	'2020-04-22 08:05:31.392264',	'2020-04-22 08:05:31.392264'),
('Puzzle',	'',	'',	'',	'de',	'2020-04-22 08:05:31.243452',	NULL,	NULL,	NULL,	1,	'Decidim::User',	1,	'2020-04-22 08:05:31.396777',	'2020-04-22 08:05:31.396777');

INSERT INTO "decidim_static_page_topics" ("title", "description", "organization_id", "weight", "show_in_footer") VALUES
('{"de": "Allgemeine Hilfe", "en": "General Help"}',	'{"de": "Lesen Sie mehr über Decidim Zürich", "en": "Read more about Decidim Zürich"}',	1,	0,	'0');

INSERT INTO "decidim_static_pages" ("title", "slug", "content", "decidim_organization_id", "created_at", "updated_at", "weight", "topic_id") VALUES
('{"de": "Standardtitel für faq", "en": "Default title for faq", "fr": "Titre par défaut pour faq", "it": "Titolo predefinito per faq"}',	'faq',	'{"de": "Fügen Sie der statischen Seite faq im Admin-Dashboard sinnvollen Inhalt hinzu.", "en": "Please add meaningful content to the faq static page on the admin dashboard.", "fr": "Ajoutez un contenu pertinent à la page faq en allant sur l''interface d''administration.", "it": "Si prega di aggiungere contenuto significativo alla pagina statica faq sul pannello di amministrazione."}',	1,	'2020-04-22 08:05:30.915424',	'2020-04-22 08:05:30.915424',	NULL,	NULL),
('{"de": "Standardtitel für terms-and-conditions", "en": "Default title for terms-and-conditions", "fr": "Titre par défaut pour terms-and-conditions", "it": "Titolo predefinito per terms-and-conditions"}',	'terms-and-conditions',	'{"de": "Fügen Sie der statischen Seite terms-and-conditions im Admin-Dashboard sinnvollen Inhalt hinzu.", "en": "Please add meaningful content to the terms-and-conditions static page on the admin dashboard.", "fr": "Ajoutez un contenu pertinent à la page terms-and-conditions en allant sur l''interface d''administration.", "it": "Si prega di aggiungere contenuto significativo alla pagina statica terms-and-conditions sul pannello di amministrazione."}',	1,	'2020-04-22 08:05:30.922317',	'2020-04-22 08:05:30.922317',	NULL,	NULL),
('{"de": "Standardtitel für accessibility", "en": "Default title for accessibility", "fr": "Titre par défaut pour accessibility", "it": "Titolo predefinito per accessibility"}',	'accessibility',	'{"de": "Fügen Sie der statischen Seite accessibility im Admin-Dashboard sinnvollen Inhalt hinzu.", "en": "Please add meaningful content to the accessibility static page on the admin dashboard.", "fr": "Ajoutez un contenu pertinent à la page accessibility en allant sur l''interface d''administration.", "it": "Si prega di aggiungere contenuto significativo alla pagina statica accessibility sul pannello di amministrazione."}',	1,	'2020-04-22 08:05:30.938337',	'2020-04-22 08:05:30.938337',	NULL,	NULL),
('{"de": "Was kann ich in Decidim Zürich?", "en": "What can I do in Decidim Zürich?"}',	'help',	'{"de": "<p>In Decidim Zürich Sie durch die Leerzeichen, die Sie im oberen Menü sehen, an verschiedenen Themen teilnehmen: Prozesse, Baugruppen, Initiativen, Konsultationen.</p> <p>In jedem Bereich finden Sie verschiedene Optionen für die Teilnahme: Vorschläge machen - einzeln oder mit anderen -, an Debatten teilnehmen, Prioritäten für umzusetzende Projekte setzen, persönliche Treffen und andere Aktionen besuchen.</p>\n", "en": "<p>In Decidim Zürich you can participate and decide on different topics, through the spaces you see in the top menu: Processes, Assemblies, Initiatives, Consultations.</p> <p>Within each one you will find different options to participate: make proposals - individually or with other people-, take part in debates, prioritize projects to implement, attend face-to-face meetings and other actions.</p>\n"}',	1,	'2020-04-22 08:05:30.95932',	'2020-04-22 08:05:30.95932',	0,	1),
('{"de": "Was ist ein partizipativer Prozess?", "en": "What is a participatory process?"}',	'participatory_processes',	'{"de": "<p>A <strong>Partizipationsprozess</strong> ist eine Folge von Partizipations Aktivitäten (zB zuerst eine Umfrage ausfüllen, dann Vorschläge machen, so dass sie diskutiert in face-to-face oder virtuellen Sitzungen, und sie schließlich die Priorisierung) mit dem Ziel , die Definition und Treffen eine Entscheidung zu einem bestimmten Thema.</p> <p>Beispiele für partizipatorische Prozesse sind: ein Verfahren zur Wahl von Ausschussmitgliedern (bei dem die Kandidaturen zuerst präsentiert, anschließend debattiert und schließlich eine Kandidatur ausgewählt wird), die Bürgerhaushalte (bei denen Vorschläge gemacht, wirtschaftlich bewertet und mit dem verfügbaren Geld abgestimmt werden). ein strategischer Planungsprozess, die gemeinschaftliche Ausarbeitung einer Vorschrift oder Norm, die Gestaltung eines städtischen Raums oder die Erstellung eines öffentlichen Planes.</p>\n", "en": "<p>A <strong>participatory process</strong> is a sequence of participatory activities (e.g. first filling out a survey, then making proposals, discussing them in face-to-face or virtual meetings, and finally prioritizing them) with the aim of defining and making a decision on a specific topic.</p> <p>Examples of participatory processes are: a process of electing committee members (where candidatures are first presented, then debated and finally a candidacy is chosen), participatory budgets (where proposals are made, valued economically and voted on with the money available), a strategic planning process, the collaborative drafting of a regulation or norm, the design of an urban space or the production of a public policy plan.</p>\n"}',	1,	'2020-04-22 08:05:30.964434',	'2020-04-22 08:05:30.964434',	NULL,	1),
('{"de": "Was sind Gremien?", "en": "What are assemblies?"}',	'assemblies',	'{"de": "<p>Eine Versammlung ist eine Gruppe von Mitgliedern einer Organisation, die sich regelmäßig treffen, um Entscheidungen über einen bestimmten Bereich oder einen bestimmten Bereich der Organisation zu treffen.</p> <p>Versammlungen halten Meetings ab, einige sind privat und andere sind offen. Wenn sie offen sind, ist es möglich, an ihnen teilzunehmen (z. B. Teilnahme, wenn die Kapazität es erlaubt, Punkte auf die Tagesordnung setzen oder Vorschläge und Entscheidungen dieses Organs kommentieren).</p> <p>Beispiele: Eine Generalversammlung (die einmal im Jahr zusammentritt, um die wichtigsten Aktionslinien der Organisation sowie ihre Exekutivorgane per Abstimmung festzulegen), ein Gleichstellungsbeirat (der alle zwei Monate zusammentritt, um Vorschläge zur Verbesserung der Geschlechterbeziehungen vorzulegen In der Organisation sind eine Evaluierungskommission (die sich jeden Monat zur Überwachung eines Prozesses trifft) oder eine Garantieeinrichtung (die Vorfälle, Missbräuche oder Vorschläge zur Verbesserung der Entscheidungsverfahren sammelt) Beispiele für Versammlungen.</p>\n", "en": "<p>An <strong>assembly</strong> is a group of members of an organization who meet periodically to make decisions about a specific area or scope of the organization.</p> <p>Assemblies hold meetings, some are private and some are open. If they are open, it is possible to participate in them (for example: attending if the capacity allows it, adding points to the agenda, or commenting on the proposals and decisions taken by this organ).</p> <p>Examples: A general assembly (which meets once a year to define the organisation''s main lines of action as well as its executive bodies by vote), an equality advisory council (which meets every two months to make proposals on how to improve gender relations in the organisation), an evaluation commission (which meets every month to monitor a process) or a guarantee body (which collects incidents, abuses or proposals to improve decision-making procedures) are all examples of assemblies.</p>\n"}',	1,	'2020-04-22 08:05:30.981305',	'2020-04-22 08:05:30.981305',	NULL,	1);

INSERT INTO decidim_users ("id", "email", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "sign_in_count", "current_sign_in_at", "last_sign_in_at", "current_sign_in_ip", "last_sign_in_ip", "created_at", "updated_at", "invitation_token", "invitation_created_at", "invitation_sent_at", "invitation_accepted_at", "invitation_limit", "invited_by_type", "invited_by_id", "invitations_count", "decidim_organization_id", "confirmation_token", "confirmed_at", "confirmation_sent_at", "unconfirmed_email", "name", "locale", "avatar", "delete_reason", "deleted_at", "admin", "managed", "roles", "nickname", "personal_url", "about", "accepted_tos_version", "newsletter_token", "newsletter_notifications_at", "type", "extended_data", "following_count", "followers_count", "notification_types", "failed_attempts", "unlock_token", "locked_at", "officialized_at", "officialized_as", "admin_terms_accepted_at", "session_token", "direct_message_types", "blocked", "blocked_at", "block_id", "follows_count", "password_updated_at") VALUES
(1, 'decidim@puzzle.ch', '$2a$11$aGN4wJ/y.2LcBPpNKEsyJeLLXOkd9aWTVuzi1OCGvewg5BmvcGeYS', null, null, null, 1, '2022-03-08 16:20:04.526549', '2022-03-07 15:50:45.957382', '172.18.0.1', '192.168.16.1', '2020-04-22 08:05:31.243452', '2022-03-08 16:20:04.526813', null, '2022-03-08 16:19:45.417054', '2022-03-08 16:19:45.417054', '2022-03-08 16:20:04.377213', null, null, null, 0, 1, null, '2020-04-22 08:49:22.492140', null, null, 'Puzzle', null, null, null, null, true, false, '{}', 'puzzle', null, null, '2020-04-22 08:05:30.922317', '', null, 'Decidim::User', '{}', 0, 0, 'all', 0, null, null, null, null, '2022-03-07 15:50:53.587949', null, 'all', false, null, null, 0, '2100-01-01 15:50:53.587949');
/* password: decidim */

INSERT INTO decidim_system_admins ("id", "email", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "failed_attempts",
                                   "unlock_token", "locked_at", "created_at", "updated_at")VALUES (1, 'decidim@puzzle.ch', '$2a$11$0YnEfBBKnhzvuUVmptI0Be5Boz6CknHnI0it31xmJLwjUnTRP/woS', NULL, NULL, NULL, 0, NULL, NULL, '2023-07-03 15:06:44.003554', '2023-07-03 15:08:08.099662');
/* password: decidim */
