---
name: Reusable Copy Images

on: 
  workflow_dispatch:
    inputs:
      sourceURI:
        description: 'Source image and tag. Example: "https://quay.io/repository/puzzle/centos-apache-modsecurity?tab=tags&tag=crs-v3.3.2-waf2"'
        required: true
      targetImage:
        description: 'Target image and tag. Example: "stbi-waf:crs-v3.3.2-waf2'
        required: true
  workflow_call:
    inputs:
      sourceURI:
        description: 'Source image and tag. Example: "https://quay.io/repository/puzzle/centos-apache-modsecurity?tab=tags&tag=crs-v3.3.2-waf2"'
        required: true
      targetImage:
        description: 'Target image and tag. Example: "stbi-waf:crs-v3.3.2-waf2'
        required: true

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:

      - name: Login Quay
        uses: docker/login-action@v1
        with:
          registry: 'quay.io'
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Login Puzzle Registry
        uses: docker/login-action@v1
        with:
          registry: registry.puzzle.ch
          username: ${{ secrets.PUZZLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PUZZLE_REGISTRY_TOKEN }}

      - name: Push image
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ${{ github.event.inputs.sourceURI }}
          dst: registry.puzzle.ch/decidim/${{ github.event.inputs.targetImage }}
...
