---
name: 'Reusable: Rails Unit Tests'

on:
  workflow_call:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        ruby: ['2.7']  # TODO: Reenable 3.0 when it's compatible

    services:
      postgres:
        image: 'postgres:11'
        env:
          POSTGRES_PASSWORD: 'postgres'
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: 'memcached'
        ports: ['11211:11211']

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up Ruby ${{ matrix.ruby }}'
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install required package
        run: |
          sudo apt-get install libpq-dev
      - name: Cache gems
        id: cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ruby-${{ matrix.ruby }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ruby-${{ matrix.ruby }}-gem-

      - name: 'Build and run tests'
        env:
          RAILS_TEST_DB_NAME: 'postgres'
          RAILS_TEST_DB_USERNAME: 'postgres'
          RAILS_TEST_DB_PASSWORD: 'postgres'
          RAILS_ENV: 'test'
        run: |
          gem install bundler --version '~> 2'
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test
