# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
    oidc:
      enabled: false
      issuer: <%= ENV["MEIN_KONTO_ISSUER"] %>
      client_id: <%= ENV["MEIN_KONTO_CLIENT_ID"] %>
      client_secret: <%= ENV["MEIN_KONTO_CLIENT_SECRET"] %>
      redirect_url: <%= ENV["MEIN_KONTO_REDIRECT_URL"] %>
  translator:
    endpoint_url: <%= ENV['TRANSLATOR_ENDPOINT_URL'] %>
    secret_key: <%= ENV['TRANSLATOR_SECRET_KEY'] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
  vapid:
    enabled: false

development:
  <<: *default
  secret_key_base: "a079b45f956a865554a9b320583d7dc7ceb61da285259731ad60ba4139cec8d57411b04dbdbe6003e10ac85d385e343c26d780e814feb4139eaee6953e9ea614"

test:
  <<: *default
  secret_key_base: "a079b45f956a865554a9b320583d7dc7ceb61da285259731ad60ba4139cec8d57411b04dbdbe6003e10ac85d385e343c26d780e814feb4139eaee6953e9ea614"
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
