questionnaire_id = 1234
questionnaire = Decidim::Forms::Questionnaire.find(questionnaire_id)

question =
  Decidim::Forms::Question.new(
    question_type: "single_option",
    mandatory: false,
    body: {"de"=>"Land", "en"=>"Country"},
    description: {"de"=>"<p>Wählen Sie Ihr Land aus.</p>", "en"=>"<p>Please select your country.</p>"},
    max_choices: nil,
    max_characters: 0
  )

answers = [
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"!dropdown! !sort!", "en"=>"!dropdown! !sort!"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Afghanistan", "en"=>"Afghanistan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ägypten", "en"=>"Egypt"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Albanien", "en"=>"Albania"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Algerien", "en"=>"Algeria"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Amerikanisch-Samoa", "en"=>"American-Samoa"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Amerikanische Jungferninseln", "en"=>"Virgin Islands (U.S.)"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Andorra", "en"=>"Andorra"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Anguilla", "en"=>"Anguilla"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Antarktis", "en"=>"Antarctica"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Antigua und Barbuda", "en"=>"Antigua and Barbuda"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Äquatorialguinea", "en"=>"Equatorial Guinea"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Argentinien", "en"=>"Argentina"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Armenien", "en"=>"Armenia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Aruba", "en"=>"Aruba"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ascension", "en"=>"Ascension"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Aserbaidschan", "en"=>"Azerbaijan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Äthiopien", "en"=>"Ethiopia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Australien", "en"=>"Australia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bahamas", "en"=>"Bahamas"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bahrain", "en"=>"Bahrain"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bangladesch", "en"=>"Bangladesh"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Barbados", "en"=>"Barbados"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Belarus", "en"=>"Belarus"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Belgien", "en"=>"Belgium"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Belize", "en"=>"Belize"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Benin", "en"=>"Benin"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bermuda", "en"=>"Bermuda"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bhutan", "en"=>"Bhutan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bolivien", "en"=>"Bolivia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bonaire, Saba & Sint Eustatius", "en"=>"Bonaire, Sint Eustatius and Saba"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bosnien und Herzegowina", "en"=>"Bosnia and Herzegovina"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Botswana", "en"=>"Botswana"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bouvetinsel", "en"=>"Bouvet Island"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Brasilien", "en"=>"Brazil"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Britische Jungferninseln", "en"=>"Virgin Islands (British)"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Britisches Territorium im Indischen Ozean", "en"=>"British Indian Ocean Territory"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Brunei", "en"=>"Brunei"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Bulgarien", "en"=>"Bulgaria"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Burkina Faso", "en"=>"Burkina Faso"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Burundi", "en"=>"Burundi"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Chile", "en"=>"Chile"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Volksrepublik China", "en"=>"China"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Cookinsel", "en"=>"Cook Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Costa Rica", "en"=>"Costa Rica"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Curaçao", "en"=>"Curaçao"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Dänemark", "en"=>"Denmark"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Deutschland", "en"=>"Germany"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Dominica", "en"=>"Dominica"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Dominikanische Republik", "en"=>"Dominican Republic"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Dschibuti", "en"=>"Djibouti"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ecuador", "en"=>"Ecuador"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Elfenbeinküste", "en"=>"Côte d'Ivoire"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"El Salvador", "en"=>"El Salvador"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Eritrea", "en"=>"Eritrea"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Estland", "en"=>"Estonia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Eswatini", "en"=>"Eswatini"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Falklandinseln", "en"=>"Falkland Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Färöer", "en"=>"Faroe Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Fidschi", "en"=>"Fiji"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Finnland", "en"=>"Finland"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Frankreich", "en"=>"France"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Französisch-Guyana", "en"=>"French Guiana"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Französisch-Polynesien", "en"=>"French Polynesia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Französische Süd- und Antarktisgebiete", "en"=>"French Southern Territories"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Gabun", "en"=>"Gabon"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Gambia", "en"=>"Gambia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Georgien", "en"=>"Georgia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ghana", "en"=>"Ghana"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Gibraltar", "en"=>"Gibraltar"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Grenada", "en"=>"Grenada"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Griechenland", "en"=>"Greece"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Grönland", "en"=>"Greenland"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guadeloupe", "en"=>"Guadeloupe"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guam", "en"=>"Guam"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guatemala", "en"=>"Guatemala"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guernsey", "en"=>"Guernsey"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guinea", "en"=>"Guinea"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guinea-Bissau", "en"=>"Guinea-Bissau"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Guyana", "en"=>"Guyana"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Haiti", "en"=>"Haiti"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Honduras", "en"=>"Honduras"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Hongkong", "en"=>"Hong Kong"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Indien", "en"=>"India"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Indonesien", "en"=>"Indonesia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Isle of Man", "en"=>"Isle of Man"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Irak", "en"=>"Iraq"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Iran", "en"=>"Iran"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Irland", "en"=>"Ireland"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Island", "en"=>"Iceland"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Israel", "en"=>"Israel"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Italien", "en"=>"Italy"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Jamaika", "en"=>"Jamaica"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Japan", "en"=>"Japan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Jemen", "en"=>"Yemen"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Jersey", "en"=>"Jersey"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Jordanien", "en"=>"Jordan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Cayman Islands", "en"=>"Cayman Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kambodscha", "en"=>"Cambodia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kamerun", "en"=>"Cameroon"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kanada", "en"=>"Canada"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kanarische Inseln", "en"=>"Canary Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kap Verde", "en"=>"Cabo Verde"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kirgisistan", "en"=>"Kyrgyzstan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kiribati", "en"=>"Kiribati"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kokosinseln", "en"=>"Cocos Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kolumbien", "en"=>"Colombia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Komoren", "en"=>"Comoros"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Demokratische Republik Kongo", "en"=>"Democratic Republic of Congo"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Republik Kongo", "en"=>"Congo"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nordkorea", "en"=>"Democratic People's Republic of Korea"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Südkorea", "en"=>"Republic of Korea"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kosovo", "en"=>"Kosovo"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kroatien", "en"=>"Croatia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kuba", "en"=>"Cuba"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Kuwait", "en"=>"Kuwait"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Laos", "en"=>"Lao People's Democratic Republic"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Lesotho", "en"=>"Lesotho"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Lettland", "en"=>"Latvia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Libanon", "en"=>"Lebanon"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Liberia", "en"=>"Liberia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Libyen", "en"=>"Libya"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Liechtenstein", "en"=>"Liechtenstein"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Litauen", "en"=>"Lithuania"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Luxemburg", "en"=>"Luxembourg"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Macau", "en"=>"Macao"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Madagaskar", "en"=>"Madagascar"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Malawi", "en"=>"Malawi"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Malaysia", "en"=>"Malaysia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Malediven", "en"=>"Maldives"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mali", "en"=>"Mali"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Malta", "en"=>"Malta"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Marokko", "en"=>"Morocco"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Marshallinseln", "en"=>"Marshall Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Martinique", "en"=>"Martinique"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mauretanien", "en"=>"Maritania"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mauritius", "en"=>"Mauritius"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mayotte", "en"=>"Mayotte"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mexiko", "en"=>"Mexico"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Föderierte Staaten von Mikronesien", "en"=>"Micronesia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Moldau", "en"=>"Moldova"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Monaco", "en"=>"Monaco"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mongolei", "en"=>"Mongolia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Montenegro", "en"=>"Montenegro"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Montserrat", "en"=>"Montserrat"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Mosambik", "en"=>"Mozambique"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Myanmar", "en"=>"Myanmar"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Namibia", "en"=>"Namibia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nauru", "en"=>"Nauru"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nepal", "en"=>"Nepal"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Neukaledonien", "en"=>"New Caledonia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Neuseeland", "en"=>"New Zealand"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nicaragua", "en"=>"Nicaragua"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Niederlande", "en"=>"Netherlands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Niger", "en"=>"Niger"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nigeria", "en"=>"Nigeria"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Niue", "en"=>"Niue"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nördliche Marianen", "en"=>"Northern Mariana Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Nordmazedonien", "en"=>"North Macedonia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Norfolkinsel", "en"=>"Norfolk Island"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Norwegen", "en"=>"Norway"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Oman", "en"=>"Oman"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Österreich", "en"=>"Austria"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Osttimor", "en"=>"Timor-Leste"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Pakistan", "en"=>"Pakistan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Palästina", "en"=>"Palestine"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Palau", "en"=>"Palau"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Panama", "en"=>"Panama"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Papua-Neuguinea", "en"=>"Papua New Guinea"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Paraguay", "en"=>"Paraguay"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Peru", "en"=>"Peru"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Philippinen", "en"=>"Philippines"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Pitcairninseln", "en"=>"Pitcairn"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Polen", "en"=>"Polan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Portugal", "en"=>"Portugal"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Puerto Rico", "en"=>"Puerto Rico"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Réunion", "en"=>"Réunion"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ruanda", "en"=>"Rwanda"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Rumänien", "en"=>"Romania"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Russland", "en"=>"Russian Federation"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Salomonen", "en"=>"Solomon Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saint-Barthélemy", "en"=>"Saint Barthélemy"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saint-Martin", "en"=>"Saint Martin"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Sambia", "en"=>"Zambia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Samoa", "en"=>"Samoa"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"San Marino", "en"=>"San Marino"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"São Tomé und Príncipe", "en"=>"São Tomé and Príncipe"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saudi-Arabien", "en"=>"Saudi Arabia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Schweden", "en"=>"Sweden"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Schweiz", "en"=>"Switzerland"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Senegal", "en"=>"Senegal"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Serbien", "en"=>"Serbia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Seychellen", "en"=>"Seychelles"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Sierra Leone", "en"=>"Sierra Leone"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Simbabwe", "en"=>"Zimbabwe"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Singapur", "en"=>"Singapore"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Sint Maarten", "en"=>"Sint Maarten"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Slowakei", "en"=>"Slovakia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Slowenien", "en"=>"Slovenia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Somalia", "en"=>"Somalia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Spanien", "en"=>"Spain"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Sri Lanka", "en"=>"Sri Lanka"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"St. Helena, Ascension und Tristan de Cunha", "en"=>"Saint Helena, Ascension and Tristan de Cunha"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saint Kitts and Nevis", "en"=>""}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saint Lucia", "en"=>""}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saint Pierre and Miquelon", "en"=>""}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Saint Vincent and the Grenadines", "en"=>""}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Südafrika", "en"=>"South Africa"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Sudan", "en"=>"Sudan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Südgeorgien und die Südlichen Sandwichinseln", "en"=>"South Georgia and the South Sandwich Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Südsudan", "en"=>"South Sudan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Suriname", "en"=>"Suriname"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Spitzbergen und Jan Mayen", "en"=>"Svalbard and Jan Mayen"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Syrien", "en"=>"Syrian Arab Republic"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tadschikistan", "en"=>"Tajikistan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Taiwan", "en"=>"Taiwan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tansania", "en"=>"Tanzania"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Thailand", "en"=>"Thailand"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Togo", "en"=>"Togo"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tokelau", "en"=>"Tokelau"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tonga", "en"=>"Tonga"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Trinidad und Tobago", "en"=>"Trinidad and Tobago"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tschad", "en"=>"Chad"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tschechien", "en"=>"Czech Republic"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tunesien", "en"=>"Tunisia"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Türkei", "en"=>"Turkey"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Turkmenistan", "en"=>"Turkmenistan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Turks- und Caicosinseln", "en"=>"Turks and Caicos Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Tuvalu", "en"=>"Tuvalu"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Uganda", "en"=>"Uganda"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ukraine", "en"=>"Ukraine"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Ungarn", "en"=>"Hungary"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"United States Minor Outlying Islands", "en"=>"United States Minor Outlying Islands"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Uruguay", "en"=>"Uruguay"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Usbekistan", "en"=>"Uzbekistan"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Vanuatu", "en"=>"Vanuatu"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Vatikanstadt", "en"=>"Vatican City"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Venezuela", "en"=>"Venezuela"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Vereinigte Arabische Emirate", "en"=>"United Arab Emirates"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Vereinigte Staaten", "en"=>"United States"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Vereinigtes Königreich", "en"=>"United Kingdom"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Vietnam", "en"=>"Viet Nam"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Wallis und Futuna", "en"=>"Wallis and Futuna"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Weihnachtsinsel", "en"=>"Christmas Island"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Westsahara", "en"=>"Western Sahara"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Zentralafrikanische Republik", "en"=>"Central African Republic"}, "free_text"=>false}),
  Decidim::Forms::AnswerOption.new({"body"=>{"de"=>"Zypern", "en"=>"Cyprus"}, "free_text"=>false})
]

question.answer_options = answers
questionnaire.questions << question