name: 'Build INT on push to master'

on:
  workflow_dispatch:
    inputs:
      image_repo:
        description: 'Image repo'
        type: string
        required: false
        default: 'https://harbor.puzzle.ch'
      image_url:
        description: 'URL to push image to'
        type: string
        required: false
        default: 'harbor.puzzle.ch/decidim/stzh-int-rails'
      configmanagement:
        description: 'Configmanagement to write image tag to'
        type: string
        required: false
        default: 'gitlab.puzzle.ch/pitc_ruby/deployments/decidim/'
      configmanagement_branch:
        description: 'Configmanagement branch to put the image tag into'
        type: string
        required: false
        default: 'main'
      kustomization_path:
        description: 'Path to kustomization file'
        type: string
        required: true
        default: './deployments/pitc-decidim-stzh-int/kustomization.yaml'
      identifier:
        description: 'Identifier for commit-message, could be a namespace or project-name'
        type: string
        required: false
        default: 'stzh-int'
      
  push:
    branches:
      - 'master'
      - 'feature/cloudscale'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-image:
    uses: ./.github/workflows/reusable_lint_test_build_update.yaml
    with:
      image_repo: ${{ inputs.image_repo || 'https://harbor.puzzle.ch' }}
      image_url: ${{ inputs.image_url || 'harbor.puzzle.ch/decidim/stzh-int-rails' }}
      configmanagement: ${{ inputs.configmanagement || 'gitlab.puzzle.ch/pitc_ruby/deployments/decidim/' }}
      configmanagement_branch: ${{ inputs.configmanagement_branch || 'main' }}
      kustomization_path: ${{ inputs.kustomization_path || './deployments/pitc-decidim-stzh-int/kustomization.yaml' }}
      identifier: ${{ inputs.identifier || 'stzh-int' }}
    secrets: inherit
