name: 'Build INT on push to master'

on:
  workflow_dispatch:
    inputs:
      image_repo:
        description: "Image repo"
        type: string
        required: true
      image_url:
        description: "URL to push image to"
        type: string
        required: true
      configmanagement:
        description: "Configmanagement to write image tag to"
        type: string
        required: true
      configmanagement_branch:
        description: "Configmanagement branch to put the image tag into"
        type: string
        required: false
      kustomization_path:
        description: "Path to kustomization file"
        type: string
        required: true
      identifier:
        description: 'Identifier for commit-message, could be a namespace or project-name'
        type: string
        required: false
        default: 'deployment'
      
  push:
    branches:
      - 'master'
      - 'feature/cloudscale'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-image:
    uses: ./.github/workflows/reusable_lint_test_build_update.yaml
    with:
      # repository: gitlab.puzzle.ch/pitc_ruby/deployments/decidim.git
      # file: ./deployments/${{ needs.settings.outputs.namespace_name }}/kustomization.yaml
      # image_tag: ${{ needs.version.outputs.version }}
      # image_ref: rails
      # identifier: ${{ needs.settings.outputs.namespace_name }}

      image_repo: "https://harbor.puzzle.ch"
      image_url: "harbor.puzzle.ch/decidim/stzh-int-rails"
      configmanagement: "gitlab.puzzle.ch/pitc_ruby/deployments/decidim/"
      configmanagement_branch: "main"
      kustomization_path: "./deployments/pitc-decidim-stzh-int/kustomization.yaml"
      identifier: "stzh-int"
    secrets: inherit
