name: 'Build INT on push to master'

on:
  push:
    branches:
      - 'master'
      - 'feature/cloudscale'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build-image:
    uses: ./.github/workflows/reusable_lint_test_build_update.yaml
    with:
      image_repo: "https://harbor.puzzle.ch"
      image_url: "harbor.puzzle.ch/decidim/stzh-int-rails"
      configmanagement: "gitlab.puzzle.ch/pitc_ruby/deployments/decidim/"
      configmanagement_branch: "main"
      kustomization_path: "./deployments/pitc-stzh-decidim-int/kustomization.yaml"
    secrets: inherit
