name: 'Build prod on release'

# TODO: In the future, copy from INT kustomization the newTag, push the image to prod and retag PROD kustomization

on:
  release:
    types:
      - released
    branches:
      - master
jobs:
  build_image:
    uses: ./.github/workflows/lint_test_build_update.yaml
    secrets: inherit
    with:
      image_repo: "harbor.puzzle.ch/decidim/stzh/prod/rails"
      configmanagement: "gitlab.puzzle.ch/pitc_ruby/deployments/decidim/"
      kustomization_path: "./deployments/pitc-stzh-decidim-prod/kustomization.yaml"
