name: 'Build prod on release'

# TODO: In the future, copy from INT kustomization the newTag, push the image to prod and retag PROD kustomization

on:
  release:
    types:
      - released
    branches:
      - master
jobs:
  build-image:
    uses: ./.github/workflows/reusable_lint_test_build_update.yaml
    with:
      image_repo: "https://harbor.puzzle.ch"
      image_url: "harbor.puzzle.ch/decidim/stzh-prod-rails"
      configmanagement: "gitlab.puzzle.ch/pitc_ruby/deployments/decidim/"
      configmanagement_branch: "main"
      kustomization_path: "./deployments/pitc-decidim-stzh-prod/kustomization.yaml"
      identifier: "stzh-prod"
    secrets: inherit
