---
name: 'Reusable: Rails Unit Tests'

on:
  workflow_call:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    services:
      postgres:
        image: 'postgis/postgis:14-3.3-alpine'
        env:
          POSTGRES_PASSWORD: 'postgres'
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
      memcached:
        image: 'memcached:alpine'
        ports: ['11211:11211']

    env:
      BUNDLE_PATH: 'vendor/bundle'
      RAILS_TEST_DB_NAME: 'postgres'
      RAILS_TEST_DB_USERNAME: 'postgres'
      RAILS_TEST_DB_PASSWORD: 'postgres'
      RAILS_ENV: 'test'


    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: 'Install required libraries'
        run: sudo apt-get install libpq-dev
      - name: 'Run tests'
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails test
