name: 'Reusable: Code Style Review'

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: 'ubuntu-latest'

    # services:
    #   postgres:
    #     image: 'postgis/postgis:14-3.3-alpine'
    #     env:
    #       POSTGRESQL_PASSWORD: 'postgres'
    #     ports: ['5432:5432']
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 10s
    #       --health-retries 10
    #   memcached:
    #     image: 'memcached:alpine'
    #     ports: ['11211:11211']

    env:
      BUNDLE_PATH: 'vendor/bundle'
      REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - run: bundle install --jobs 4 --retry 3
      - uses: reviewdog/action-rubocop@v2.12.0
        with:
          reporter: github-pr-review
          level: error
          reviewdog_flags: '-diff="git diff $DIFF_BRANCH"'
          rubocop_extensions: rubocop-rails rubocop-performance rubocop-rspec rubocop-i18n rubocop-rake rubocop-faker