name: 'Lint, test and build image. Push image tag to configmanagement'

on:
  workflow_call:
    inputs:
      image_repo:
        description: "Image repo"
        type: string
        required: true
      image_url:
        description: "URL to push image to"
        type: string
        required: true
      configmanagement:
        description: "Configmanagement to write image tag to"
        type: string
        required: true
      configmanagement_branch:
        description: "Configmanagement branch to put the image tag into"
        type: string
        required: false
      kustomization_path:
        description: "Path to kustomization file"
        type: string
        required: true

jobs: 
  lint:
    uses: ./.github/workflows/reusable_lint.yaml
  test:
    uses: ./.github/workflows/reusable_tests.yaml
  build:
    needs: [lint, test]
    uses: ./.github/workflows/reusable_build.yaml
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
    with:
      repository_url: ${{ inputs.image_repo }}
      images: ${{ inputs.image_url }}
      flavor: latest=true

  extract_info:
    needs: [build]
    runs-on: 'ubuntu-latest'
    outputs:
      version: ${{ steps.extracted.outputs.version }}
    steps:
      - name: Save JSON
        run: echo '${{ needs.build.outputs.json }}' > build_info.json
      - name: Extract version
        id: get_version
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '(.tags[] | select(. | test("sha-"))) | sub(".*(sha-.*)","${1}")' build_info.json
      - name: Prepare outputs
        id: extracted
        run: echo 'version=${{ steps.get_version.outputs.result }}' >> "$GITHUB_OUTPUT"

  update_tag:
    needs: [build, extract_info]
    uses: ./.github/workflows/reusable_update_image.yaml
    secrets: inherit
    with:
      repository: ${{ inputs.configmanagement }}
      repository_branch: ${{ inputs.configmanagement_branch }}
      file: ${{ inputs.kustomization_path }}
      image_tag: ${{ needs.extract_info.outputs.version }}
