name: 'Lint and test on pull request'

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - 'master'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  lint:
    uses: ./.github/workflows/reusable_lint.yaml
  test:
    uses: ./.github/workflows/reusable_tests.yaml
